### ISSUE TITLE
Expected WERs?

### ISSUE THREAD

**Issue by svenha** [tudarmstadt-lt/kaldi-tuda-de#1]
Hi. Thanks for the excellent scripts. Worked very nicely with current kaldi. But I am unsure about the word error rates: the best line in RESULTS... is:
%WER 19.47 [ 3428 / 17605, 850 ins, 295 del, 2283 sub ] exp/sgmm_5a_mmi_b0.1/decode4/wer_13
Should the expected WERs be added to the REAME.md or similar?
Ciao
Sven

**Comment by bmilde** [comment]
Yes, that is in line with the results we observed, we have a WER comparison in [this paper](https://www.lt.informatik.tu-darmstadt.de/fileadmin/user_upload/Group_LangTech/publications/Radeck-ArnethEtAl_TSD2015_SpeechCorpus.pdf) that was done using the scripts here.

Some minor bugs were improved and Kaldi got a bit better since then, so that you should actually get a little bit better results now. Thanks for letting me know, I will add the new results to the README.md soon.

**Comment by bmilde** [comment]
I've added RESULTS.me.2015-11-24-11-44-47 to the repository  - it reflects the expected WER with SGMM-HMM models, i.e. without using deep learning.
