### ISSUE TITLE
feats.scp no such file or directory

### ISSUE THREAD

**Issue by jufrit** [tudarmstadt-lt/kaldi-tuda-de#12]
Hi, using the tuda scripts and Im currently trying to add more data.
To do so, I have generated xml- and wav files of the form: 
2017-01-01-0-0-23.xml  and  2017-01-01-0-0-23_Kinect-Beam.wav
I have quite many files, around 90k... 

Now, when I add just a few files, everything works just fine, but once I add more than around 40k 
I get an error somewhere around steps/compute_cmvn_stats.sh because feats.scp is not created for some reason. 

ERROR (apply-cmvn[5.1.80~1-e5275]:SequentialTableReader():util/kaldi-table-inl.h:876) Error constructing TableReader: rspecifier is scp:data/train/split8/1/feats.scp

Do you have hint on why this happens?

Thanks already for your help.
Viele Grüße aus Erlangen, Julian

**Comment by MikitaKurlovich** [comment]
Hi @jufrit! I have the same issue. Did you have any suggestions about how to fix the problem?

Thanks!

**Comment by bmilde** [comment]
Hi, are you using the latest version? I recently added "set -euxo pipefail"
to the run.sh script, so that the script aborts on the first error. Before
that minor problems could cause some scripts to fail, but run.sh would
continue execution. So for example the tuda scripts will fail and produce
empty files if you did not install the python dependencies (as explained in
the README): pip3 install beautifulsoup4 lxml

But without the pipefail, the run script would continue and you might not
notice the error.

Am Di., 8. Okt. 2019 um 11:31 Uhr schrieb Mikita Kurlovich <
notifications@github.com>:
