### ISSUE TITLE
The wav files have bad headers

### ISSUE THREAD

**Issue by RuABraun** [tudarmstadt-lt/kaldi-tuda-de#19]
Running `wav-to-duration` fails with `<wavfile> has no duration in header`. Running it with `read_entire_file=true` still results in an error: `WaveData: expected 4-byte chunk-name, got read error`

I'm a bit perplexed why this happening, `soxi` and `ffprobe` work on the tuda wav files, but despite `wav-to-duration` working for tons of other wav files that I have they only fail on most of the tuda ones?

**Comment by jborbik** [comment]
I have the same issue, should we suppress this error, adding the permissive (p, ) option to the rspecifier?

**Comment by jborbik** [comment]
In my case the problem has been fixed by removing the following tuda corpus files:
2014-03-27-11-50-33*
2014-06-17-13-46-27*
2014-03-24-13-39-24*

They were either empty or very short.
I am working on the cleaned script, which solves a couple of problems. I'll open push request as soon as it is ready :)

EDIT: Pull request: https://github.com/uhh-lt/kaldi-tuda-de/pull/23

**Comment by bmilde** [comment]
Thanks again for the PR
