### ISSUE TITLE
DNN models

### ISSUE THREAD

**Issue by svenha** [tudarmstadt-lt/kaldi-tuda-de#7]
Has anybody succeeded in building DNN models with tuda-de?
What performance (WER) is achievable?

**Comment by hadiasheri** [comment]
I have just trained the dnn model:
%WER 18.69 [ 3290 / 17605, 702 ins, 417 del, 2171 sub ]
%SER 77.13 [ 833 / 1080 ]

**Comment by svenha** [comment]
Thanks for reporting!
The values are somewhat disappointing because they are not much better than for sgmm.

This is my best result so far:
tri3b_dnn_2048x5_smb/decode_6/wer_14: %WER 17.51 [ 3083 / 17605, 690 ins, 343 del, 2050 sub ]

I know that some people have found annotation problems in the corpus; they are trying to report them to the corpus maintainers. Let's see if it is integrated upstream.

**Comment by AASHISHAG** [comment]
@svenha, @hadiasheri : Did you try running the latest script s5_r2/run.sh? How are the results?

**Comment by bmilde** [comment]
You should be able to get about %WER 15.9 with the newest models and data on Tuda-test, without any RNN-LM rescoring. It should be a bit better than that if you rescore, haven't tested it yet. Note that these numbers are not comparable to the old ~20% WERs from the s5 recipe, as the old recipe assumed the best case scenario of no OOVs in test, i.e. all test words also appear in the dictionary. That is obviously not a good way to test things and the new s5_r2 recipe report WER more truthfully.

Note that many errors in the test corpus are OOVs at this point, noun compounding seems to be the culprit in many of those and these usually add up quickly (e.g. Rechtsschutzversicherung vs. Recht Schutz Versicherung, 3 errors with one substitution and two insertions)

**Comment by AASHISHAG** [comment]
@bmilde @maggieezzat Thank you for the response. I tried running the latest s5_r2 recipe but got error on the last step of TDNN training. Somehow data/train_cleaned/feats.scp is not created and I am not sure of it. I tried running run.sh step by step but didn't find the exact answer. Could you please help. I ran the script with just Tuda-de corpus and kept all other flags to false.  (Attached-logs.txt)

[Logs.txt](https://github.com/uhh-lt/kaldi-tuda-de/files/3230455/Logs.txt)

```
.local/get_utt2dur.sh: data/train/utt2dur already exists with the expected length.  We won't recompute it.
steps/cleanup/clean_and_segment_data.sh: expected file exp/tri4/final.mdl to exist.
steps/compute_cmvn_stats.sh data/train_cleaned exp/make_mfcc/train_cleaned mfcc
make_cmvn.sh: no such file data/train_cleaned/feats.scp
local/get_utt2dur.sh: Expected data/train_cleaned/wav.scp, data/train_cleaned/segments or data/train_cleaned/feats.scp to exist
local/get_reco2dur.sh: Expected data/train_cleaned/wav.scp to exist
./local/run_cleanup_segmentation.sh: line 58: data/train_cleaned/recordings: No such file or directory
steps/align_fmllr.sh --nj 24 --cmd utils/run.pl data/train_cleaned data/lang_300k4 exp/tri4 exp/tri4_ali_cleaned
cat: data/lang_300k4/oov.int: No such file or directory
steps/train_sat.sh --cmd utils/run.pl 5000 100000 data/train_cleaned data/lang_300k4 exp/tri4_ali_cleaned exp/tri4_cleaned
train_sat.sh: no such file data/train_cleaned/feats.scp
mkgraph.sh: expected data/lang_300k4_test_pron/L.fst to exist
steps/decode_fmllr.sh --nj 12 --num-threads 4 --cmd utils/run.pl --num-threads 4 exp/tri4_cleaned/graph data/dev exp/tri4_cleaned/decode_dev
cat: exp/tri4_cleaned/graph/phones/silence.csl: No such file or directory
steps/decode_fmllr.sh --nj 12 --num-threads 4 --cmd utils/run.pl --num-threads 4 exp/tri4_cleaned/graph data/test exp/tri4_cleaned/decode_test
cat: exp/tri4_cleaned/graph/phones/silence.csl: No such file or directory
Now running TDNN chain data preparation, i-vector training and TDNN-HMM training
./local/run_tdnn_1f.sh --lang_dir data/lang_300k4
local/run_ivector_common.sh: expected file data/train_cleaned/feats.scp to exist
(env3.5.2) root@kaldi-gpu:/home/rsa-key-20181219/kaldi-trunk/egs/kaldi-tuda-de/s5_r2#
```

**Comment by bmilde** [comment]
Is data/wav/german-speechdata-package-v2 there with all the wav and xml
files?

Am Di., 28. Mai 2019 um 23:46 Uhr schrieb Aashish Agarwal <
notifications@github.com>:

**Comment by AASHISHAG** [comment]
@bmilde : Yes, `data/wav/german-speechdata-package-v2` is there will all the wav's and xml files in three different folders `train, test and dev`. That's why the script (run.sh) passed through all the MFCC creation steps. 

Could you please point out, in which step is `data/train_cleaned/feats.scp` created? or something else you could point out from the logs?

**Comment by maggieezzat** [comment]
@AASHISHAG some of the wav files are corrputed and maybe that's why you get erros, I ended up using the data with another model, but here is the list of corrupted files, it caused me errors with the other model and I had to remove them:
[corrupted.txt](https://github.com/uhh-lt/kaldi-tuda-de/files/3234277/corrupted.txt)
[corrupted2.txt](https://github.com/uhh-lt/kaldi-tuda-de/files/3234278/corrupted2.txt)

**Comment by AASHISHAG** [comment]
@maggieezzat : Thank you for sharing the files. I removed these corrupted files from the dataset but unfortunately again got errors. I don't know if I am missing anything. Can I request you to please share the model you created with the German dataset. It would be really helpful.

**Comment by AASHISHAG** [comment]
@bmilde : I dig a bit inside and want to point you to one of the might be known issue. Please guide.

I have cleared some samples from Tuda-De corpus, as pointed out by @maggieezzat. Now, my total count is `54406` as opposed to what is mentioned here i.e. `55526`. https://github.com/uhh-lt/kaldi-tuda-de/blob/e8e15f6a8e53ffc0966e0dca46aa91d1c7ab5f1e/s5_r2/run.sh#L424

Also, since I am using only Tuda-de corpus, the count of the files is less than 150000 
as used in the below code. Because of which the most of the code starting from here is failing, as, I believe, the code is expecting other corpus (SWC etc) as well.   https://github.com/uhh-lt/kaldi-tuda-de/blob/e8e15f6a8e53ffc0966e0dca46aa91d1c7ab5f1e/s5_r2/run.sh#L435. 
https://github.com/uhh-lt/kaldi-tuda-de/blob/e8e15f6a8e53ffc0966e0dca46aa91d1c7ab5f1e/s5_r2/run.sh#L436
https://github.com/uhh-lt/kaldi-tuda-de/blob/e8e15f6a8e53ffc0966e0dca46aa91d1c7ab5f1e/s5_r2/run.sh#L440

Could you please point out if I need to skip some part of the code, to experiment with just Tuda-De corpus?

**Comment by AASHISHAG** [comment]
@bmilde : Requesting guidance here. This time I ran the script *./run.sh* with all the data and didn't do any changes but on reaching line [https://github.com/uhh-lt/kaldi-tuda-de/blob/master/s5_r2/run.sh#L615]

```
if [ $stage -le 16 ]; then
  echo "Cleanup the corpus"
  ./local/run_cleanup_segmentation.sh --langdir ${lang_dir}
fi
```

I got the following error. The lattices were created successfully in `exp/tri4_cleaned_work` but since the `data/train_cleaned` folder was empty, therefore the `exp/tri4_ali_cleaned` and `exp/tri4_cleaned` folders were also empty with no dev and test WER. 

```
run.pl: job failed, log is in exp/tri4_cleaned_work/log/taint_ctm_edits.log
steps/compute_cmvn_stats.sh data/train_cleaned exp/make_mfcc/train_cleaned mfcc
make_cmvn.sh: no such file data/train_cleaned/feats.scp
local/get_utt2dur.sh: Expected data/train_cleaned/wav.scp, data/train_cleaned/segments or data/train_cleaned/feats.scp to exist
```

When I checked the log file as pointed out in the error, it shows UnicodeDecodeError. Could you please advice.

```
# steps/cleanup/internal/taint_ctm_edits.py exp/tri4_cleaned_work/ctm_edits.modified exp/tri4_cleaned_work/ctm_edits.tainted 
# Started at Thu Jun 13 05:11:24 CEST 2019
#
Traceback (most recent call last):
  File "steps/cleanup/internal/taint_ctm_edits.py", line 247, in <module>
    ProcessData()
  File "steps/cleanup/internal/taint_ctm_edits.py", line 154, in ProcessData
    first_line = f_in.readline()
  File "/media/data/agarwal/python-environments/env3.5.2/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 303: ordinal not in range(128)
# Accounting: time=1 threads=1
# Ended (code 1) at Thu Jun 13 05:11:25 CEST 2019, elapsed time 1 seconds
```

**Comment by AASHISHAG** [comment]
@bmilde @milde @Jendker : could any one please help on the above issue, I am getting the above error at [https://github.com/uhh-lt/kaldi-tuda-de/blob/master/s5_r2/run.sh#L615] 

```
if [ $stage -le 16 ]; then
  echo "Cleanup the corpus"
  ./local/run_cleanup_segmentation.sh --langdir ${lang_dir}
fi
```

**Comment by jborbik** [comment]
I am not sure what could go wrong here. Have a look on https://groups.google.com/forum/#!forum/kaldi-help maybe someone has asked similar question or ask for guidance there.

**Comment by milde** [comment]
Looks like your Python installation is making problems and I would guess
your locales are broken or not set to unicode.

See also:
How to solve UnicodeDecodeError in Python 3.6?
<https://stackoverflow.com/questions/51026315/how-to-solve-unicodedecodeerror-in-python-3-6/51027262#51027262>

Am Do., 13. Juni 2019 um 14:28 Uhr schrieb Jędrzej Beniamin Orbik <
notifications@github.com>:

**Comment by AASHISHAG** [comment]
@milde @bmilde : Unfortunately, I am unable to solve the error. But I am trying to run your model. Is there any direct way to test/transcribe any speech file without using Gstreamer?

**Comment by AASHISHAG** [comment]
@bmilde @milde : Kindly help.

**Comment by bmilde** [comment]
> Is there any direct way to test/transcribe any speech file without using Gstreamer?

You can try https://github.com/gooofy/py-kaldi-asr

**Comment by bmilde** [comment]
There is also PyKaldi, I recently used it and liked it very much. We have created our own kaldi-model-server with it now to load nnet3 models: https://github.com/uhh-lt/kaldi-model-server
